import { SocialVibe, SocialStatus, BarType } from "@prisma/client";
import { UserSocialProfileWithRelations } from "@/types/social";

export const mockUsers: UserSocialProfileWithRelations[] = [
  {
    id: "user-1",
    userId: "user-1",
    bio: "Love craft beer and good conversations",
    vibe: SocialVibe.CHILL,
    interests: ["Craft Beer", "Live Music", "Board Games"],
    isSocialMode: true,
    socialStatus: SocialStatus.SOCIAL_MODE,
    lastActive: new Date(),
    locationLat: 60.1699,
    locationLng: 24.9384,
    currentBarId: "bar-1",
    currentBar: {
      id: "bar-1",
      name: "Siltanen",
      address: "Helsinki City Center",
      type: BarType.LIVE_MUSIC,
    },
    isVisibleOnMap: true,
    maxDistance: 1000,
    createdAt: new Date(),
    updatedAt: new Date(),
    user: {
      id: "user-1",
      name: "Alex",
      image: "/avatars/alex.jpg",
    },
    distance: 250,
  },
  {
    id: "user-2",
    userId: "user-2",
    bio: "Always up for dancing and meeting new people",
    vibe: SocialVibe.PARTY,
    interests: ["Dancing", "Cocktails", "Socializing"],
    isSocialMode: true,
    socialStatus: SocialStatus.SOCIAL_MODE,
    lastActive: new Date(Date.now() - 15 * 60 * 1000), // 15 minutes ago
    locationLat: 60.1685,
    locationLng: 24.939,
    currentBarId: "bar-2",
    currentBar: {
      id: "bar-2",
      name: "Bar Loose",
      address: "Helsinki City Center",
      type: BarType.CLUB,
    },
    isVisibleOnMap: true,
    maxDistance: 1000,
    createdAt: new Date(),
    updatedAt: new Date(),
    user: {
      id: "user-2",
      name: "Mika",
      image: "/avatars/mika.jpg",
    },
    distance: 450,
  },
  {
    id: "user-3",
    userId: "user-3",
    bio: "Tech entrepreneur looking to network",
    vibe: SocialVibe.NETWORKING,
    interests: ["Business", "Whiskey", "Startups"],
    isSocialMode: true,
    socialStatus: SocialStatus.SOCIAL_MODE,
    lastActive: new Date(Date.now() - 5 * 60 * 1000), // 5 minutes ago
    locationLat: 60.1702,
    locationLng: 24.9378,
    currentBarId: "bar-3",
    currentBar: {
      id: "bar-3",
      name: "Liberty or Death",
      address: "Helsinki City Center",
      type: BarType.COCKTAIL_BAR,
    },
    isVisibleOnMap: true,
    maxDistance: 1000,
    createdAt: new Date(),
    updatedAt: new Date(),
    user: {
      id: "user-3",
      name: "Sarah",
      image: "/avatars/sarah.jpg",
    },
    distance: 320,
  },
  {
    id: "user-4",
    userId: "user-4",
    bio: "Group of friends looking to meet others",
    vibe: SocialVibe.CASUAL,
    interests: ["Beer", "Social Games", "Meeting New People"],
    isSocialMode: true,
    socialStatus: SocialStatus.SOCIAL_MODE,
    lastActive: new Date(Date.now() - 10 * 60 * 1000), // 10 minutes ago
    locationLat: 60.1695,
    locationLng: 24.94,
    currentBarId: "bar-4",
    currentBar: {
      id: "bar-4",
      name: "Kaisla",
      address: "Helsinki City Center",
      type: BarType.PUB,
    },
    isVisibleOnMap: true,
    maxDistance: 1000,
    createdAt: new Date(),
    updatedAt: new Date(),
    user: {
      id: "user-4",
      name: "Group of 3",
      image: "/avatars/group.jpg",
    },
    distance: 600,
  },
  {
    id: "user-5",
    userId: "user-5",
    bio: "Traveler exploring Helsinki nightlife",
    vibe: SocialVibe.ADVENTUROUS,
    interests: ["Travel", "Local Culture", "Craft Cocktails"],
    isSocialMode: true,
    socialStatus: SocialStatus.SOCIAL_MODE,
    lastActive: new Date(Date.now() - 25 * 60 * 1000), // 25 minutes ago
    locationLat: 60.171,
    locationLng: 24.9395,
    currentBarId: null,
    currentBar: null,
    isVisibleOnMap: true,
    maxDistance: 1000,
    createdAt: new Date(),
    updatedAt: new Date(),
    user: {
      id: "user-5",
      name: "Emma",
      image: "/avatars/emma.jpg",
    },
    distance: 780,
  },
];

export const mockBars = [
  {
    id: "bar-1",
    name: "Siltanen",
    type: BarType.LIVE_MUSIC,
    activeUsers: 3,
    heatLevel: 75,
  },
  {
    id: "bar-2",
    name: "Bar Loose",
    type: BarType.CLUB,
    activeUsers: 2,
    heatLevel: 60,
  },
  {
    id: "bar-3",
    name: "Liberty or Death",
    type: BarType.COCKTAIL_BAR,
    activeUsers: 1,
    heatLevel: 40,
  },
  {
    id: "bar-4",
    name: "Kaisla",
    type: BarType.PUB,
    activeUsers: 4,
    heatLevel: 85,
  },
];

// Mock current user location (Helsinki city center)
export const mockCurrentLocation = {
  lat: 60.1699,
  lng: 24.9384,
};
