[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"

[[services]]
name = "socket-server"
httpPort = 3001

[services.env]
PORT = "3001"

[services.healthcheck]
path = "/health"
initialDelay = 30
period = 30
timeout = 10